name: Install Dependencies
description: Installs SDKs & local Uno.Check

inputs:
  target-platform:
    description: 'See available values at https://platform.uno/docs/articles/external/uno.check/doc/using-uno-check.html'
    required: false
    default: 'all'
  dotnet-version:
    description: '.NET SDK version'
    required: false
    default: '9.0.x'
  sdkVersion:
    description: 'Windows SDK version'
    required: false
    default: '22621'

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3

  - name: Setup .NET 9
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: 9.0.x

  - name: Install Uno.Check from repo copy
    shell: pwsh
    run: |
      $nupkgDir = "$env:GITHUB_WORKSPACE/.github"
      dotnet tool install -g uno.check `
           --add-source $nupkgDir `
           --version 1.0.0 `
           --ignore-failed-sources
      uno-check -v --ci --non-interactive --fix --target all --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates

